export default [
  {
    img: "./food1.jpg",
    time: "23 minutes",
    author: "Gidado",
    description:
      "A zesty tart with a buttery crust, filled with a tangy lemon-lime custard and topped with a light dusting of powdered sugar.",
    ingredients:
      "Tart crust, lemon juice, lime juice, eggs, sugar, butter, powdered sugar.",
    detail: "Citrus Burst Tart",
    type: "Dessert",
  },
  {
    img: "./food2.jpg",
    time: "30 minutes",
    author: "Chef Luca Bianchi",
    description:
      "A vibrant salad featuring fresh mango slices, mixed greens, and a tangy lime vinaigrette, topped with crunchy almonds and feta cheese.",
    ingredients:
      "Mango, mixed greens, almonds, feta cheese, lime juice, olive oil, honey.",
    detail: "Mango Tango Salad",
    type: "Lunch",
  },
  {
    img: "./food3.jpg",
    time: "1 hour",
    author: "Chef Sofia Da Costa",
    description:
      "A fresh and flavorful pasta dish featuring al dente penne tossed with a vibrant basil pesto and a medley of seasonal vegetables.",
    ingredients:
      "Penne pasta, basil pesto, cherry tomatoes, bell peppers, zucchini, Parmesan cheese.",
    detail: "Basil Pesto Primavera",
    type: "Dinner",
  },
  {
    img: "./food4.jpg",
    time: "33 minutes",
    author: "Chef Isabella Reyes",
    description:
      "A refreshing sorbet made with lemon juice and a hint of lavender, perfect for a light and elegant summer treat.",
    ingredients: "Lemon juice, lavender buds, sugar, water.",
    detail: "Lavender Lemonade Sorbet",
    type: "Dessert",
    viewHome: true,
  },
  {
    img: "./food5.jpg",
    time: "45 minutes",
    author: "Chef Mia Andersen",
    description:
      "Savory bacon wrapped around sweet maple-glazed chunks of chicken or vegetables, baked until crispy and caramelized.",
    ingredients:
      "Bacon, maple syrup, chicken or vegetables, brown sugar, black pepper.",
    detail: "Smoked Maple Bacon Bites",
    type: "Appetizer",
    viewHome: true,
  },
  {
    img: "./food6.jpg",
    time: "27 minutes",
    author: "Chef Marco Rossi",
    description: "",
    ingredients: "",
    detail: "Citrus Burst Tart",
    type: "Dessert",
  },
  {
    img: "./food7.jpg",
    detail: "Spaghetti Bolognese",
    author: "John Doe",
    time: "30 mins",
    description: "A classic Italian pasta dish with a rich, meaty sauce.",
    ingredients:
      "Spaghetti, ground beef, tomato sauce, garlic, onions, olive oil",
    type: "Dinner",
  },
  {
    img: "./food8.jpg",
    detail: "Grilled Chicken Salad",
    author: "Jane Smith",
    time: "20 mins",
    description: "A healthy and refreshing salad with grilled chicken breast.",
    ingredients:
      "Chicken breast, mixed greens, cherry tomatoes, cucumber, olive oil",
    type: "Lunch",
  },
  {
    img: "./food9.jpg",
    detail: "Chocolate Cake",
    author: "Sara Lee",
    time: "1 hr",
    description: "A rich and moist chocolate cake for dessert lovers.",
    ingredients: "Flour, cocoa powder, sugar, eggs, butter, baking powder",
    type: "Dessert",
  },
  {
    img: "./food10.jpg",
    detail: "Beef Stew",
    author: "Mark Brown",
    time: "2 hrs",
    description: "A hearty and warming beef stew with vegetables.",
    ingredients: "Beef, potatoes, carrots, onions, beef broth, garlic",
    type: "Dinner",
    viewHome: true,
  },
  {
    img: "./food11.jpg",
    detail: "Caesar Salad",
    author: "Lisa White",
    time: "15 mins",
    description:
      "A classic Caesar salad with crispy croutons and creamy dressing.",
    ingredients: "Romaine lettuce, croutons, Parmesan cheese, Caesar dressing",
    type: "Lunch",
    viewHome: true,
  },
  {
    img: "./food12.jpg",
    detail: "Pancakes",
    author: "Tom Green",
    time: "20 mins",
    description: "Fluffy pancakes perfect for a weekend breakfast.",
    ingredients: "Flour, milk, eggs, butter, baking powder, sugar",
    type: "Breakfast",
  },
  {
    img: "./food13.jpg",
    detail: "Lemon Tart",
    author: "Emma Davis",
    time: "45 mins",
    description: "A tangy and sweet lemon tart with a buttery crust.",
    ingredients: "Lemon, sugar, eggs, butter, flour",
    type: "Dessert",
  },
  {
    img: "./food14.jpg",
    detail: "Chicken Curry",
    author: "James Wilson",
    time: "1 hr",
    description: "A flavorful and spicy chicken curry served with rice.",
    ingredients: "Chicken, curry powder, coconut milk, onions, garlic, ginger",
    type: "Dinner",
  },
  {
    img: "./food15.jpg",
    detail: "Vegetable Stir-Fry",
    author: "Olivia Johnson",
    time: "25 mins",
    description: "A quick and healthy vegetable stir-fry with a savory sauce.",
    ingredients: "Mixed vegetables, soy sauce, garlic, ginger, olive oil",
    type: "Lunch",
  },
  {
    img: "./food16.jpg",
    detail: "Berry Smoothie",
    author: "Sophia Martinez",
    time: "10 mins",
    description: "A refreshing smoothie made with mixed berries and yogurt.",
    ingredients: "Mixed berries, yogurt, honey, ice",
    type: "Breakfast",
  },
  {
    img: "./food17.jpg",
    detail: "Beef Tacos",
    author: "Michael Garcia",
    time: "30 mins",
    description: "Delicious beef tacos with all your favorite toppings.",
    ingredients:
      "Ground beef, taco seasoning, tortillas, lettuce, cheese, salsa",
    type: "Dinner",
  },
  {
    img: "./food18.jpg",
    detail: "Spinach Quiche",
    author: "Isabella Taylor",
    time: "1 hr 15 mins",
    description: "A savory quiche with spinach and cheese in a flaky crust.",
    ingredients: "Spinach, eggs, cheese, pie crust, milk, onions",
    type: "Breakfast",
  },
  {
    img: "./food19.jpg",
    detail: "Stuffed Bell Peppers",
    author: "Chef Liam O'Connor",
    time: "1 hr 10 mins",
    description:
      "Colorful bell peppers stuffed with a savory mix of rice, ground beef, and vegetables, baked to perfection.",
    ingredients: "Bell peppers, ground beef, rice, onions, tomatoes, cheese",
    type: "Dinner",
  },
  {
    img: "./food20.jpg",
    detail: "Avocado Toast",
    author: "Chef Emily Carter",
    time: "15 mins",
    description:
      "A simple yet delicious toast topped with mashed avocado, cherry tomatoes, and a sprinkle of sea salt.",
    ingredients: "Bread, avocado, cherry tomatoes, olive oil, sea salt",
    type: "Breakfast",
  },
  ,
  {
    img: "./food20.jpg",
    detail: "Avocado Toast",
    author: "Chef Emily Carter",
    time: "15 mins",
    description:
      "A simple yet delicious toast topped with mashed avocado, cherry tomatoes, and a sprinkle of sea salt.",
    ingredients: "Bread, avocado, cherry tomatoes, olive oil, sea salt",
    type: "Breakfast",
  },
];
